package com.serenityai.data.models

import java.util.Date

/**
 * UC32: AI-Generated Journaling Prompts - Data Models
 * 
 * Represents journaling prompts generated by AI, personalized based on user mood,
 * preferences, and journaling history.
 */
data class JournalingPrompt(
    val id: String = "",
    val title: String,
    val prompt: String, // The actual prompt text/question
    val category: PromptCategory,
    val moodTags: List<MoodTag>,
    val difficulty: PromptDifficulty,
    val estimatedTime: Int, // Minutes
    val isAIGenerated: Boolean = true,
    val timesUsed: Int = 0,
    val effectivenessScore: Float = 0f, // 0-1.0 based on user engagement
    val generatedAt: Date = Date(),
    val personalizedFor: String? = null, // User ID if personalized
    val personalizationFactors: List<PersonalizationFactor> = emptyList()
)

enum class PromptCategory {
    REFLECTION,
    GRATITUDE,
    GROWTH,
    RELATIONSHIPS,
    GOALS,
    CHALLENGES,
    EMOTIONAL_PROCESSING,
    DAILY_CHECK_IN,
    ALL
}

enum class MoodTag {
    HAPPY,
    SAD,
    ANXIOUS,
    GRATEFUL,
    MOTIVATED,
    STRESSED,
    CALM,
    OVERWHELMED,
    ALL
}

enum class PromptDifficulty {
    EASY,
    MEDIUM,
    HARD,
    ADVANCED
}

data class PersonalizationFactor(
    val type: FactorType,
    val value: String,
    val weight: Float // 0-1.0, how much this factor influenced the prompt
)

enum class FactorType {
    MOOD_PATTERN,
    RECENT_MOOD,
    JOURNALING_HISTORY,
    USER_PREFERENCE,
    TIME_OF_DAY,
    DAY_OF_WEEK,
    RECENT_EVENTS
}

data class PromptGenerationRequest(
    val userId: String,
    val currentMood: Int? = null, // 1-10 scale
    val moodTags: List<MoodTag> = emptyList(),
    val preferredCategory: PromptCategory? = null,
    val preferredDifficulty: PromptDifficulty? = null,
    val maxTimeMinutes: Int? = null,
    val excludeUsedPrompts: Boolean = false,
    val customTheme: String? = null
)

data class PromptRecommendation(
    val userId: String,
    val recommendedPrompts: List<JournalingPrompt>,
    val reasons: List<String> = emptyList(),
    val personalizationScore: Float = 0f, // 0-1.0
    val generatedAt: Date = Date()
)

